name: Continuous Integration
run-name: ${{ github.actor }} istesting out GitHub Actions for CEFIM
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm run start
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm lint /backend/index.js
            - run: npm lint /frontend/index.html
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm run test