name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions for CEFIM

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Installation de NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 20.x
                cache: npm
            - name: Installation des dépendances
              run: npm install
            - name: Build
              run: npm run build
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Installation de NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 20.x
                cache: npm
            - name: Installation des dépendances
              run: npm install
            - name: Lint
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Installation de NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 20.x
                cache: npm
            - name: Installation des dépendances
              run: npm install
            - name: Test
              run: npm run test