name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions for CEFIM
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm run start
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: cd backend/
            - run: npm run lint index.js
            - run: cd ../frontend/
            - run: npm run lint index.html
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm run test