name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions for CEFIM
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm install
            - run: npm run start
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm install
            - run: npm run lint -w backend
            - run: npm run lint -w frontend
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm install
            - run: npm run test