name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions for CEFIM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS, mise en cache et dépendances
        uses: ./.github/actions/setup-node
      - name: Build
        run: npm run build -w backend
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS, mise en cache et dépendances
        uses: ./.github/actions/setup-node
      - name: Build
        run: npm run build -w frontend
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS, mise en cache et dépendances
        uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run lint -w backend
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS, mise en cache et dépendances
        uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run lint -w frontend
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS, mise en cache et dépendances
        uses: ./.github/actions/setup-node
      - name: Test
        run: npm run test -w backend
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS, mise en cache et dépendances
        uses: ./.github/actions/setup-node
      - name: Test
        run: npm run test -w frontend
